"""Load structured news transcript data generated by the scraper."""

from __future__ import annotations

from dataclasses import dataclass
import json
import re
from pathlib import Path

from bs4 import BeautifulSoup


@dataclass
class NewsItem:
    """One structured news item from the transcript."""

    title: str
    content_html: str
    url: str
    content_text: str


@dataclass
class NewsTranscript:
    """Structured data for one day's news broadcast transcript."""

    date: str
    abstract: str
    items: list[NewsItem]
    updated_at: str | None = None


def load_transcript(path: str | Path) -> NewsTranscript:
    """Load the JSON transcript generated by the Node scraper."""
    transcript_path = Path(path)
    if not transcript_path.exists():
        raise FileNotFoundError(f"Transcript JSON not found: {transcript_path}")

    payload = json.loads(transcript_path.read_text(encoding="utf-8"))
    items = [
        NewsItem(
            title=(item.get("title") or "").strip(),
            content_html=item.get("content") or "",
            url=item.get("url") or "",
            content_text=html_to_text(item.get("content") or ""),
        )
        for item in payload.get("items", [])
    ]
    return NewsTranscript(
        date=str(payload.get("date") or "").strip(),
        abstract=(payload.get("abstract") or "").strip(),
        items=items,
        updated_at=payload.get("updatedAt"),
    )


def html_to_text(html: str) -> str:
    """Convert the CCTV HTML snippet into readable plain text."""
    if not html:
        return ""

    soup = BeautifulSoup(html, "lxml")
    text = soup.get_text("\n", strip=True)
    text = text.replace("\xa0", " ")
    text = re.sub(r"\n{2,}", "\n", text)
    return text.strip()
