"""Load structured news transcript data generated by the scraper."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from bs4 import BeautifulSoup


@dataclass
class NewsItem:
    """One structured news item from the transcript."""

    title: str
    content_html: str
    url: str
    content_text: str


@dataclass
class NewsTranscript:
    """Structured data for one day's news broadcast transcript."""

    date: str
    abstract: str
    items: list[NewsItem]
    updated_at: str | None = None


def load_transcript(path: str | Path) -> NewsTranscript:
    """Load a transcript from either JSON or markdown."""
    transcript_path = Path(path)
    if not transcript_path.exists():
        raise FileNotFoundError(f"Transcript file not found: {transcript_path}")

    if transcript_path.suffix.lower() == ".md":
        return _load_markdown_transcript(transcript_path)
    return _load_json_transcript(transcript_path)


def resolve_transcript_path(path: str | Path) -> Path:
    """Resolve a preferred transcript path, falling back from JSON to markdown."""
    transcript_path = Path(path)
    if transcript_path.exists():
        return transcript_path

    if transcript_path.suffix.lower() == ".json":
        markdown_path = transcript_path.with_suffix(".md")
        if markdown_path.exists():
            return markdown_path

    raise FileNotFoundError(
        f"Transcript file not found: {transcript_path} "
        f"(also checked: {transcript_path.with_suffix('.md')})"
    )


def _load_json_transcript(transcript_path: Path) -> NewsTranscript:
    """Load the JSON transcript generated by the Node scraper."""
    payload = json.loads(transcript_path.read_text(encoding="utf-8"))
    items = [
        NewsItem(
            title=(item.get("title") or "").strip(),
            content_html=item.get("content") or "",
            url=item.get("url") or "",
            content_text=html_to_text(item.get("content") or ""),
        )
        for item in payload.get("items", [])
    ]
    return NewsTranscript(
        date=str(payload.get("date") or "").strip(),
        abstract=(payload.get("abstract") or "").strip(),
        items=items,
        updated_at=payload.get("updatedAt"),
    )


def _load_markdown_transcript(transcript_path: Path) -> NewsTranscript:
    """Parse an existing markdown transcript file into structured data."""
    raw = transcript_path.read_text(encoding="utf-8")
    date_match = re.search(r"^# 《新闻联播》 \((\d{8})\)", raw, re.MULTILINE)
    abstract_match = re.search(
        r"## 新闻摘要\s*(.*?)\s*## 详细新闻",
        raw,
        re.DOTALL,
    )
    details_match = re.search(r"## 详细新闻\s*(.*)$", raw, re.DOTALL)

    if not date_match or not details_match:
        raise ValueError(f"Unrecognized transcript markdown format: {transcript_path}")

    items = _parse_markdown_items(details_match.group(1))
    return NewsTranscript(
        date=date_match.group(1),
        abstract=(abstract_match.group(1).strip() if abstract_match else ""),
        items=items,
        updated_at=None,
    )


def _parse_markdown_items(section_text: str) -> list[NewsItem]:
    """Parse the detailed-news section from the markdown transcript."""
    pattern = re.compile(
        r"^### (?P<title>.+?)\n\n(?P<body>.*?)(?:\n\n\[查看原文\]\((?P<url>https?://[^\)]+)\))?(?=\n\n### |\n\n---|\Z)",
        re.DOTALL | re.MULTILINE,
    )
    items: list[NewsItem] = []
    for match in pattern.finditer(section_text.strip()):
        title = match.group("title").strip()
        body = match.group("body").strip()
        url = (match.group("url") or "").strip()
        items.append(
            NewsItem(
                title=title,
                content_html=body,
                url=url,
                content_text=html_to_text(body),
            )
        )
    return items


def html_to_text(html: str) -> str:
    """Convert the CCTV HTML snippet into readable plain text."""
    if not html:
        return ""

    soup = BeautifulSoup(html, "lxml")
    text = soup.get_text("\n", strip=True)
    text = text.replace("\xa0", " ")
    text = re.sub(r"\n{2,}", "\n", text)
    return text.strip()
